const express = require("express");
const ejs = require("ejs");
const bodyParser = require("body-parser");
const app = express();

app.use(express.static("public")); //for static files
app.use(bodyParser.urlencoded({ extended: true }));

app.set("view engine", "ejs");

const note = {
    title: "Day 1 - I am great as Fuck",
    content: `Its the first ever note to Every reader asks questions at a story’s beginning. Some are basic: What is Hogwarts? Who is Dumbledore? Why does Voldemort hate Harry? Whereas others are more specific. In Harry Potter and the Goblet of Fire, readers wonder who at Hogwarts is trying to kill Harry. This important question offers an opportunity to steer readers toward the wrong solution and distract them from the right one. An unanticipated outcome is the definition of a plot twist at its core.
        The goblet of fire chooses Harry to compete in the potentially lethal Triwizard Tournament that is being hosted at his school. This convinces Harry and his friends that his foe is attempting to murder him on behalf of the true monster, the spirit of Voldemort.         
        When Harry becomes one of the tournament winners, he’s transported to a graveyard, where a resurrected Voldemort nearly destroys him. After Harry survives, his enemy, who had been disguised as Professor Moody, reveals himself. Barty Crouch Jr. manipulated the goblet and the tournament so he could use Harry’s blood to revive Lord Voldemort. He put Harry in danger, not to kill him, but to guide him to He Who Must Not Be Named.   
        Incidents that previously seemed unrelated now become deeper. Cedric, Hagrid, and Dobby aided Harry in overcoming the tournament challenges, unknowingly pushing him toward victory and his fight with Voldemort. Readers assumed his friends were being helpful, but their advice originated from Crouch Jr.
        This plot twist addresses the question readers believed was already solved (who are Harry’s allies?) 
        Its the first ever note to Every reader asks questions at a story’s beginning. Some are basic: What is Hogwarts? Who is Dumbledore? Why does Voldemort hate Harry? Whereas others are more specific. In Harry Potter and the Goblet of Fire, readers wonder who at Hogwarts is trying to kill Harry. This important question offers an opportunity to steer readers toward the wrong solution and distract them from the right one. An unanticipated outcome is the definition of a plot twist at its core.
        The goblet of fire chooses Harry to compete in the potentially lethal Triwizard Tournament that is being hosted at his school. This convinces Harry and his friends that his foe is attempting to murder him on behalf of the true monster, the spirit of Voldemort.         
        When Harry becomes one of the tournament winners, he’s transported to a graveyard, where a resurrected Voldemort nearly destroys him. After Harry survives, his enemy, who had been disguised as Professor Moody, reveals himself. Barty Crouch Jr. manipulated the goblet and the tournament so he could use Harry’s blood to revive Lord Voldemort. He put Harry in danger, not to kill him, but to guide him to He Who Must Not Be Named.   
        Incidents that previously seemed unrelated now become deeper. Cedric, Hagrid, and Dobby aided Harry in overcoming the tournament challenges, unknowingly pushing him toward victory and his fight with Voldemort. Readers assumed his friends were being helpful, but their advice originated from Crouch Jr.
        This plot twist addresses the question readers believed was already solved (who are Harry’s allies?) and the one yet to be resolved (who is targeting Harry?). It’s memorable because it startles readers, yet they also realize they overlooked the evidence that was staring them in the face. If Rowling hadn’t inserted a bucketful of clues, her reveals would have been less impressive. be DIsplayed on the App The -f is actually required because of the rebase. Whenever you do a rebase you would need to do a force push because the remote branch cannot be fast-forwarded to your commit. You'd always want to make sure that you do a pull before pushing, but if you don't like to force push to master or dev for that matter, you can create a new branch to push to and then merge or make a PR
        Its the first ever note to Every reader asks questions at a story’s beginning. Some are basic: What is Hogwarts? Who is Dumbledore? Why does Voldemort hate Harry? Whereas others are more specific. In Harry Potter and the Goblet of Fire, readers wonder who at Hogwarts is trying to kill Harry. This important question offers an opportunity to steer readers toward the wrong solution and distract them from the right one. An unanticipated outcome is the definition of a plot twist at its core.
        The goblet of fire chooses Harry to compete in the potentially lethal Triwizard Tournament that is being hosted at his school. This convinces Harry and his friends that his foe is attempting to murder him on behalf of the true monster, the spirit of Voldemort.         
        When Harry becomes one of the tournament winners, he’s transported to a graveyard, where a resurrected Voldemort nearly destroys him. After Harry survives, his enemy, who had been disguised as Professor Moody, reveals himself. Barty Crouch Jr. manipulated the goblet and the tournament so he could use Harry’s blood to revive Lord Voldemort. He put Harry in danger, not to kill him, but to guide him to He Who Must Not Be Named.   
        Incidents that previously seemed unrelated now become deeper. Cedric, Hagrid, and Dobby aided Harry in overcoming the tournament challenges, unknowingly pushing him toward victory and his fight with Voldemort. Readers assumed his friends were being helpful, but their advice originated from Crouch Jr.
        This plot twist addresses the question readers believed was already solved (who are Harry’s allies?) and the one yet to be resolved (who is targeting Harry?). It’s memorable because it startles readers, yet they also realize they overlooked the evidence that was staring them in the face. If Rowling hadn’t inserted a bucketful of clues, her reveals would have been less impressive. be DIsplayed on the App The -f is actually required because of the rebase. Whenever you do a rebase you would need to do a force push because the remote branch cannot be fast-forwarded to your commit. You'd always want to make sure that you do a pull before pushing, but if you don't like to force push to master or dev for that matter, you can create a new branch to push to and then merge or make a PR
        Its the first ever note to Every reader asks questions at a story’s beginning. Some are basic: What is Hogwarts? Who is Dumbledore? Why does Voldemort hate Harry? Whereas others are more specific. In Harry Potter and the Goblet of Fire, readers wonder who at Hogwarts is trying to kill Harry. This important question offers an opportunity to steer readers toward the wrong solution and distract them from the right one. An unanticipated outcome is the definition of a plot twist at its core.
        The goblet of fire chooses Harry to compete in the potentially lethal Triwizard Tournament that is being hosted at his school. This convinces Harry and his friends that his foe is attempting to murder him on behalf of the true monster, the spirit of Voldemort.         
        When Harry becomes one of the tournament winners, he’s transported to a graveyard, where a resurrected Voldemort nearly destroys him. After Harry survives, his enemy, who had been disguised as Professor Moody, reveals himself. Barty Crouch Jr. manipulated the goblet and the tournament so he could use Harry’s blood to revive Lord Voldemort. He put Harry in danger, not to kill him, but to guide him to He Who Must Not Be Named.   
        Incidents that previously seemed unrelated now become deeper. Cedric, Hagrid, and Dobby aided Harry in overcoming the tournament challenges, unknowingly pushing him toward victory and his fight with Voldemort. Readers assumed his friends were being helpful, but their advice originated from Crouch Jr.
        This plot twist addresses the question readers believed was already solved (who are Harry’s allies?) and the one yet to be resolved (who is targeting Harry?). It’s memorable because it startles readers, yet they also realize they overlooked the evidence that was staring them in the face. If Rowling hadn’t inserted a bucketful of clues, her reveals would have been less impressive. be DIsplayed on the App The -f is actually required because of the rebase. Whenever you do a rebase you would need to do a force push because the remote branch cannot be fast-forwarded to your commit. You'd always want to make sure that you do a pull before pushing, but if you don't like to force push to master or dev for that matter, you can create a new branch to push to and then merge or make a PR
        Its the first ever note to Every reader asks questions at a story’s beginning. Some are basic: What is Hogwarts? Who is Dumbledore? Why does Voldemort hate Harry? Whereas others are more specific. In Harry Potter and the Goblet of Fire, readers wonder who at Hogwarts is trying to kill Harry. This important question offers an opportunity to steer readers toward the wrong solution and distract them from the right one. An unanticipated outcome is the definition of a plot twist at its core.
        The goblet of fire chooses Harry to compete in the potentially lethal Triwizard Tournament that is being hosted at his school. This convinces Harry and his friends that his foe is attempting to murder him on behalf of the true monster, the spirit of Voldemort.         
        When Harry becomes one of the tournament winners, he’s transported to a graveyard, where a resurrected Voldemort nearly destroys him. After Harry survives, his enemy, who had been disguised as Professor Moody, reveals himself. Barty Crouch Jr. manipulated the goblet and the tournament so he could use Harry’s blood to revive Lord Voldemort. He put Harry in danger, not to kill him, but to guide him to He Who Must Not Be Named.   
        Incidents that previously seemed unrelated now become deeper. Cedric, Hagrid, and Dobby aided Harry in overcoming the tournament challenges, unknowingly pushing him toward victory and his fight with Voldemort. Readers assumed his friends were being helpful, but their advice originated from Crouch Jr.
        This plot twist addresses the question readers believed was already solved (who are Harry’s allies?) and the one yet to be resolved (who is targeting Harry?). It’s memorable because it startles readers, yet they also realize they overlooked the evidence that was staring them in the face. If Rowling hadn’t inserted a bucketful of clues, her reveals would have been less impressive. be DIsplayed on the App The -f is actually required because of the rebase. Whenever you do a rebase you would need to do a force push because the remote branch cannot be fast-forwarded to your commit. You'd always want to make sure that you do a pull before pushing, but if you don't like to force push to master or dev for that matter, you can create a new branch to push to and then merge or make a PR
        Its the first ever note to Every reader asks questions at a story’s beginning. Some are basic: What is Hogwarts? Who is Dumbledore? Why does Voldemort hate Harry? Whereas others are more specific. In Harry Potter and the Goblet of Fire, readers wonder who at Hogwarts is trying to kill Harry. This important question offers an opportunity to steer readers toward the wrong solution and distract them from the right one. An unanticipated outcome is the definition of a plot twist at its core.
        The goblet of fire chooses Harry to compete in the potentially lethal Triwizard Tournament that is being hosted at his school. This convinces Harry and his friends that his foe is attempting to murder him on behalf of the true monster, the spirit of Voldemort.         
        When Harry becomes one of the tournament winners, he’s transported to a graveyard, where a resurrected Voldemort nearly destroys him. After Harry survives, his enemy, who had been disguised as Professor Moody, reveals himself. Barty Crouch Jr. manipulated the goblet and the tournament so he could use Harry’s blood to revive Lord Voldemort. He put Harry in danger, not to kill him, but to guide him to He Who Must Not Be Named.   
        Incidents that previously seemed unrelated now become deeper. Cedric, Hagrid, and Dobby aided Harry in overcoming the tournament challenges, unknowingly pushing him toward victory and his fight with Voldemort. Readers assumed his friends were being helpful, but their advice originated from Crouch Jr.
        This plot twist addresses the question readers believed was already solved (who are Harry’s allies?) and the one yet to be resolved (who is targeting Harry?). It’s memorable because it startles readers, yet they also realize they overlooked the evidence that was staring them in the face. If Rowling hadn’t inserted a bucketful of clues, her reveals would have been less impressive. be DIsplayed on the App The -f is actually required because of the rebase. Whenever you do a rebase you would need to do a force push because the remote branch cannot be fast-forwarded to your commit. You'd always want to make sure that you do a pull before pushing, but if you don't like to force push to master or dev for that matter, you can create a new branch to push to and then merge or make a PR
        Its the first ever note to Every reader asks questions at a story’s beginning. Some are basic: What is Hogwarts? Who is Dumbledore? Why does Voldemort hate Harry? Whereas others are more specific. In Harry Potter and the Goblet of Fire, readers wonder who at Hogwarts is trying to kill Harry. This important question offers an opportunity to steer readers toward the wrong solution and distract them from the right one. An unanticipated outcome is the definition of a plot twist at its core.
        The goblet of fire chooses Harry to compete in the potentially lethal Triwizard Tournament that is being hosted at his school. This convinces Harry and his friends that his foe is attempting to murder him on behalf of the true monster, the spirit of Voldemort.         
        When Harry becomes one of the tournament winners, he’s transported to a graveyard, where a resurrected Voldemort nearly destroys him. After Harry survives, his enemy, who had been disguised as Professor Moody, reveals himself. Barty Crouch Jr. manipulated the goblet and the tournament so he could use Harry’s blood to revive Lord Voldemort. He put Harry in danger, not to kill him, but to guide him to He Who Must Not Be Named.   
        Incidents that previously seemed unrelated now become deeper. Cedric, Hagrid, and Dobby aided Harry in overcoming the tournament challenges, unknowingly pushing him toward victory and his fight with Voldemort. Readers assumed his friends were being helpful, but their advice originated from Crouch Jr.
        This plot twist addresses the question readers believed was already solved (who are Harry’s allies?) and the one yet to be resolved (who is targeting Harry?). It’s memorable because it startles readers, yet they also realize they overlooked the evidence that was staring them in the face. If Rowling hadn’t inserted a bucketful of clues, her reveals would have been less impressive. be DIsplayed on the App The -f is actually required because of the rebase. Whenever you do a rebase you would need to do a force push because the remote branch cannot be fast-forwarded to your commit. You'd always want to make sure that you do a pull before pushing, but if you don't like to force push to master or dev for that matter, you can create a new branch to push to and then merge or make a PR
        Its the first ever note to Every reader asks questions at a story’s beginning. Some are basic: What is Hogwarts? Who is Dumbledore? Why does Voldemort hate Harry? Whereas others are more specific. In Harry Potter and the Goblet of Fire, readers wonder who at Hogwarts is trying to kill Harry. This important question offers an opportunity to steer readers toward the wrong solution and distract them from the right one. An unanticipated outcome is the definition of a plot twist at its core.
        The goblet of fire chooses Harry to compete in the potentially lethal Triwizard Tournament that is being hosted at his school. This convinces Harry and his friends that his foe is attempting to murder him on behalf of the true monster, the spirit of Voldemort.         
        When Harry becomes one of the tournament winners, he’s transported to a graveyard, where a resurrected Voldemort nearly destroys him. After Harry survives, his enemy, who had been disguised as Professor Moody, reveals himself. Barty Crouch Jr. manipulated the goblet and the tournament so he could use Harry’s blood to revive Lord Voldemort. He put Harry in danger, not to kill him, but to guide him to He Who Must Not Be Named.   
        Incidents that previously seemed unrelated now become deeper. Cedric, Hagrid, and Dobby aided Harry in overcoming the tournament challenges, unknowingly pushing him toward victory and his fight with Voldemort. Readers assumed his friends were being helpful, but their advice originated from Crouch Jr.
        This plot twist addresses the question readers believed was already solved (who are Harry’s allies?) and the one yet to be resolved (who is targeting Harry?). It’s memorable because it startles readers, yet they also realize they overlooked the evidence that was staring them in the face. If Rowling hadn’t inserted a bucketful of clues, her reveals would have been less impressive. be DIsplayed on the App The -f is actually required because of the rebase. Whenever you do a rebase you would need to do a force push because the remote branch cannot be fast-forwarded to your commit. You'd always want to make sure that you do a pull before pushing, but if you don't like to force push to master or dev for that matter, you can create a new branch to push to and then merge or make a PR
        Its the first ever note to Every reader asks questions at a story’s beginning. Some are basic: What is Hogwarts? Who is Dumbledore? Why does Voldemort hate Harry? Whereas others are more specific. In Harry Potter and the Goblet of Fire, readers wonder who at Hogwarts is trying to kill Harry. This important question offers an opportunity to steer readers toward the wrong solution and distract them from the right one. An unanticipated outcome is the definition of a plot twist at its core.
        The goblet of fire chooses Harry to compete in the potentially lethal Triwizard Tournament that is being hosted at his school. This convinces Harry and his friends that his foe is attempting to murder him on behalf of the true monster, the spirit of Voldemort.         
        When Harry becomes one of the tournament winners, he’s transported to a graveyard, where a resurrected Voldemort nearly destroys him. After Harry survives, his enemy, who had been disguised as Professor Moody, reveals himself. Barty Crouch Jr. manipulated the goblet and the tournament so he could use Harry’s blood to revive Lord Voldemort. He put Harry in danger, not to kill him, but to guide him to He Who Must Not Be Named.   
        Incidents that previously seemed unrelated now become deeper. Cedric, Hagrid, and Dobby aided Harry in overcoming the tournament challenges, unknowingly pushing him toward victory and his fight with Voldemort. Readers assumed his friends were being helpful, but their advice originated from Crouch Jr.
        This plot twist addresses the question readers believed was already solved (who are Harry’s allies?) and the one yet to be resolved (who is targeting Harry?). It’s memorable because it startles readers, yet they also realize they overlooked the evidence that was staring them in the face. If Rowling hadn’t inserted a bucketful of clues, her reveals would have been less impressive. be DIsplayed on the App The -f is actually required because of the rebase. Whenever you do a rebase you would need to do a force push because the remote branch cannot be fast-forwarded to your commit. You'd always want to make sure that you do a pull before pushing, but if you don't like to force push to master or dev for that matter, you can create a new branch to push to and then merge or make a PR
        Its the first ever note to Every reader asks questions at a story’s beginning. Some are basic: What is Hogwarts? Who is Dumbledore? Why does Voldemort hate Harry? Whereas others are more specific. In Harry Potter and the Goblet of Fire, readers wonder who at Hogwarts is trying to kill Harry. This important question offers an opportunity to steer readers toward the wrong solution and distract them from the right one. An unanticipated outcome is the definition of a plot twist at its core.
        The goblet of fire chooses Harry to compete in the potentially lethal Triwizard Tournament that is being hosted at his school. This convinces Harry and his friends that his foe is attempting to murder him on behalf of the true monster, the spirit of Voldemort.         
        When Harry becomes one of the tournament winners, he’s transported to a graveyard, where a resurrected Voldemort nearly destroys him. After Harry survives, his enemy, who had been disguised as Professor Moody, reveals himself. Barty Crouch Jr. manipulated the goblet and the tournament so he could use Harry’s blood to revive Lord Voldemort. He put Harry in danger, not to kill him, but to guide him to He Who Must Not Be Named.   
        Incidents that previously seemed unrelated now become deeper. Cedric, Hagrid, and Dobby aided Harry in overcoming the tournament challenges, unknowingly pushing him toward victory and his fight with Voldemort. Readers assumed his friends were being helpful, but their advice originated from Crouch Jr.
        This plot twist addresses the question readers believed was already solved (who are Harry’s allies?) and the one yet to be resolved (who is targeting Harry?). It’s memorable because it startles readers, yet they also realize they overlooked the evidence that was staring them in the face. If Rowling hadn’t inserted a bucketful of clues, her reveals would have been less impressive. be DIsplayed on the App The -f is actually required because of the rebase. Whenever you do a rebase you would need to do a force push because the remote branch cannot be fast-forwarded to your commit. You'd always want to make sure that you do a pull before pushing, but if you don't like to force push to master or dev for that matter, you can create a new branch to push to and then merge or make a PR
        Its the first ever note to Every reader asks questions at a story’s beginning. Some are basic: What is Hogwarts? Who is Dumbledore? Why does Voldemort hate Harry? Whereas others are more specific. In Harry Potter and the Goblet of Fire, readers wonder who at Hogwarts is trying to kill Harry. This important question offers an opportunity to steer readers toward the wrong solution and distract them from the right one. An unanticipated outcome is the definition of a plot twist at its core.
        The goblet of fire chooses Harry to compete in the potentially lethal Triwizard Tournament that is being hosted at his school. This convinces Harry and his friends that his foe is attempting to murder him on behalf of the true monster, the spirit of Voldemort.         
        When Harry becomes one of the tournament winners, he’s transported to a graveyard, where a resurrected Voldemort nearly destroys him. After Harry survives, his enemy, who had been disguised as Professor Moody, reveals himself. Barty Crouch Jr. manipulated the goblet and the tournament so he could use Harry’s blood to revive Lord Voldemort. He put Harry in danger, not to kill him, but to guide him to He Who Must Not Be Named.   
        Incidents that previously seemed unrelated now become deeper. Cedric, Hagrid, and Dobby aided Harry in overcoming the tournament challenges, unknowingly pushing him toward victory and his fight with Voldemort. Readers assumed his friends were being helpful, but their advice originated from Crouch Jr.
        This plot twist addresses the question readers believed was already solved (who are Harry’s allies?) and the one yet to be resolved (who is targeting Harry?). It’s memorable because it startles readers, yet they also realize they overlooked the evidence that was staring them in the face. If Rowling hadn’t inserted a bucketful of clues, her reveals would have been less impressive. be DIsplayed on the App The -f is actually required because of the rebase. Whenever you do a rebase you would need to do a force push because the remote branch cannot be fast-forwarded to your commit. You'd always want to make sure that you do a pull before pushing, but if you don't like to force push to master or dev for that matter, you can create a new branch to push to and then merge or make a PR
        Its the first ever note to Every reader asks questions at a story’s beginning. Some are basic: What is Hogwarts? Who is Dumbledore? Why does Voldemort hate Harry? Whereas others are more specific. In Harry Potter and the Goblet of Fire, readers wonder who at Hogwarts is trying to kill Harry. This important question offers an opportunity to steer readers toward the wrong solution and distract them from the right one. An unanticipated outcome is the definition of a plot twist at its core.
        The goblet of fire chooses Harry to compete in the potentially lethal Triwizard Tournament that is being hosted at his school. This convinces Harry and his friends that his foe is attempting to murder him on behalf of the true monster, the spirit of Voldemort.         
        When Harry becomes one of the tournament winners, he’s transported to a graveyard, where a resurrected Voldemort nearly destroys him. After Harry survives, his enemy, who had been disguised as Professor Moody, reveals himself. Barty Crouch Jr. manipulated the goblet and the tournament so he could use Harry’s blood to revive Lord Voldemort. He put Harry in danger, not to kill him, but to guide him to He Who Must Not Be Named.   
        Incidents that previously seemed unrelated now become deeper. Cedric, Hagrid, and Dobby aided Harry in overcoming the tournament challenges, unknowingly pushing him toward victory and his fight with Voldemort. Readers assumed his friends were being helpful, but their advice originated from Crouch Jr.
        This plot twist addresses the question readers believed was already solved (who are Harry’s allies?) and the one yet to be resolved (who is targeting Harry?). It’s memorable because it startles readers, yet they also realize they overlooked the evidence that was staring them in the face. If Rowling hadn’t inserted a bucketful of clues, her reveals would have been less impressive. be DIsplayed on the App The -f is actually required because of the rebase. Whenever you do a rebase you would need to do a force push because the remote branch cannot be fast-forwarded to your commit. You'd always want to make sure that you do a pull before pushing, but if you don't like to force push to master or dev for that matter, you can create a new branch to push to and then merge or make a PR
        Its the first ever note to Every reader asks questions at a story’s beginning. Some are basic: What is Hogwarts? Who is Dumbledore? Why does Voldemort hate Harry? Whereas others are more specific. In Harry Potter and the Goblet of Fire, readers wonder who at Hogwarts is trying to kill Harry. This important question offers an opportunity to steer readers toward the wrong solution and distract them from the right one. An unanticipated outcome is the definition of a plot twist at its core.
        The goblet of fire chooses Harry to compete in the potentially lethal Triwizard Tournament that is being hosted at his school. This convinces Harry and his friends that his foe is attempting to murder him on behalf of the true monster, the spirit of Voldemort.         
        When Harry becomes one of the tournament winners, he’s transported to a graveyard, where a resurrected Voldemort nearly destroys him. After Harry survives, his enemy, who had been disguised as Professor Moody, reveals himself. Barty Crouch Jr. manipulated the goblet and the tournament so he could use Harry’s blood to revive Lord Voldemort. He put Harry in danger, not to kill him, but to guide him to He Who Must Not Be Named.   
        Incidents that previously seemed unrelated now become deeper. Cedric, Hagrid, and Dobby aided Harry in overcoming the tournament challenges, unknowingly pushing him toward victory and his fight with Voldemort. Readers assumed his friends were being helpful, but their advice originated from Crouch Jr.
        This plot twist addresses the question readers believed was already solved (who are Harry’s allies?) and the one yet to be resolved (who is targeting Harry?). It’s memorable because it startles readers, yet they also realize they overlooked the evidence that was staring them in the face. If Rowling hadn’t inserted a bucketful of clues, her reveals would have been less impressive. be DIsplayed on the App The -f is actually required because of the rebase. Whenever you do a rebase you would need to do a force push because the remote branch cannot be fast-forwarded to your commit. You'd always want to make sure that you do a pull before pushing, but if you don't like to force push to master or dev for that matter, you can create a new branch to push to and then merge or make a PR
        Its the first ever note to Every reader asks questions at a story’s beginning. Some are basic: What is Hogwarts? Who is Dumbledore? Why does Voldemort hate Harry? Whereas others are more specific. In Harry Potter and the Goblet of Fire, readers wonder who at Hogwarts is trying to kill Harry. This important question offers an opportunity to steer readers toward the wrong solution and distract them from the right one. An unanticipated outcome is the definition of a plot twist at its core.
        The goblet of fire chooses Harry to compete in the potentially lethal Triwizard Tournament that is being hosted at his school. This convinces Harry and his friends that his foe is attempting to murder him on behalf of the true monster, the spirit of Voldemort.         
        When Harry becomes one of the tournament winners, he’s transported to a graveyard, where a resurrected Voldemort nearly destroys him. After Harry survives, his enemy, who had been disguised as Professor Moody, reveals himself. Barty Crouch Jr. manipulated the goblet and the tournament so he could use Harry’s blood to revive Lord Voldemort. He put Harry in danger, not to kill him, but to guide him to He Who Must Not Be Named.   
        Incidents that previously seemed unrelated now become deeper. Cedric, Hagrid, and Dobby aided Harry in overcoming the tournament challenges, unknowingly pushing him toward victory and his fight with Voldemort. Readers assumed his friends were being helpful, but their advice originated from Crouch Jr.
        This plot twist addresses the question readers believed was already solved (who are Harry’s allies?) and the one yet to be resolved (who is targeting Harry?). It’s memorable because it startles readers, yet they also realize they overlooked the evidence that was staring them in the face. If Rowling hadn’t inserted a bucketful of clues, her reveals would have been less impressive. be DIsplayed on the App The -f is actually required because of the rebase. Whenever you do a rebase you would need to do a force push because the remote branch cannot be fast-forwarded to your commit. You'd always want to make sure that you do a pull before pushing, but if you don't like to force push to master or dev for that matter, you can create a new branch to push to and then merge or make a PR
        and the one yet to be resolved (who is targeting Harry?). It’s memorable because it startles readers, yet they also realize they overlooked the evidence that was staring them in the face. If Rowling hadn’t inserted a bucketful of clues, her reveals would have been less impressive. be DIsplayed on the App The -f is actually required because of the rebase. Whenever you do a rebase you would need to do a force push because the remote branch cannot be fast-forwarded to your commit. You'd always want to make sure that you do a pull before pushing, but if you don't like to force push to master or dev for that matter, you can create a new branch to push to and then merge or make a PR.`,
    date: "3-sep-22",
    tags: ["great", "note", "sadd", "asdd", "sdasdad"],
};

const notes = [
    note,
    {
        title: "Day 2",
        content:
            "kahgdgakd asohd asdha soduhas oduash doasgd uasgdi asdgas odgaou saudg asohds",
        date: "2-dec-22",
        tags: ["personal", "code", "fuck"],
    },
    {
        title: "Day 3",
        content:
            "kahgdgakd aasldh oahsd uhas odha doasuhdasuodhas odhasd asohdas oudhas duosahd oasudgh asufgduifgdsiuf daiufgha ofhao dfhaoudf asoudfha sododgaou saudg asohds",
        date: "2-jan-23",
        tags: ["school", "crush", "friends"],
    },
];

app.get("/", function (req, res) {
    res.render("home", {
        notes: notes
    });
});

app.listen(3000, function () {
    console.log("app started @ localhost 3000");
});
